### ISSUE TITLE
ValueError: index can't contain negative values

### ISSUE THREAD

**Issue by ianier** [onnx/tensorflow-onnx#1108]
When trying to convert the Spleeter 2-stem model I get the error below. The frozen model can be found [here](https://1drv.ms/u/s!Aja0hpIlYElLhIRR2jmpfjim2VJlzA?e=8RA7SD).

Here's the command line I tried:

python -m tf2onnx.convert --input \models\spleeter_2stems.pb --output \models\spleeter_2stems.onnx --inputs Placeholder:0 --outputs strided_slice_13:0, strided_slice_23:0

Traceback (most recent call last):
  File "...\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\Python37\site-packages\tf2onnx\convert.py", line 185, in <module>
    main()
  File "...\Python37\site-packages\tf2onnx\convert.py", line 163, in main
    const_node_values=const_node_values)
  File "...\Python37\site-packages\tf2onnx\tfonnx.py", line 410, in process_tf_graph
    outputs_to_values, outputs_to_dtypes = compute_const_folding_using_tf(tf_graph, const_node_values)
  File "...\Python37\site-packages\tf2onnx\tf_utils.py", line 159, in compute_const_folding_using_tf
    outputs_to_values[node.outputs[0].name] = get_tf_tensor_data(tensor)
  File "...\Python37\site-packages\tf2onnx\tf_utils.py", line 71, in get_tf_tensor_data
    np_data = tensor_util.MakeNdarray(tensor)
  File "...\Python37_64\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 645, in MakeNdarray
    values = np.pad(values, (0, num_elements - values.size), "edge")
  File "<__array_function__ internals>", line 6, in pad
  File "...\Python37_64\lib\site-packages\numpy\lib\arraypad.py", line 746, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "...\Python37_64\lib\site-packages\numpy\lib\arraypad.py", line 513, in _as_pairs
    raise ValueError("index can't contain negative values")
ValueError: index can't contain negative values

Any ideas?

**Comment by guschmue** [comment]
This raises in tensorflow/MakeNdarray when we ask tensorflow to give us a numpy array for a Constant tensor stft/frame/zeros_1 that is of shape [0, 2].
It raises because num_elements = 0.
Could you take a look at  stft/frame/zeros_1 in the model source if it is correct?

**Comment by guschmue** [comment]
Just looking at the PR mentioned above - it should fix this. But I belief the root cause is the shape of [0,2]

**Comment by ianier** [comment]
@guschmue; I think the relevant code is [this](https://github.com/deezer/spleeter/blob/ca5cdd7d2894790d08a2f91d32132230e77dd861/spleeter/model/__init__.py#L278), so from what I understand the shape should be [stft/frame_length, 2] (stft/frame_length in the frozen model is a const = 4096).
In Netron, the shape of  stft/frame/zeros_1 is shown as [?,2], which I think confirms my understanding:
![image](https://user-images.githubusercontent.com/23641015/94330806-0aebf780-ffc8-11ea-96aa-5bd7a152f733.png)

**Comment by ianier** [comment]
@guschmue: I went ahead and installed @xadupre branch:

pip uninstall tf2onnx
pip install git+https://github.com/xadupre/tensorflow-onnx@foldb

Converting the same model now produces the following error message:

 INFO - compute_const_folding_using_tf: get_tf_tensor_data failed for node 'stft/frame/zeros_1', replace by an array([], shape=(0, 2), dtype=int32)
Traceback (most recent call last):
  File "...\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\convert.py", line 185, in <module>
    main()
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\convert.py", line 163, in main
    const_node_values=const_node_values)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\tfonnx.py", line 411, in process_tf_graph
    outputs_to_values, outputs_to_dtypes = compute_const_folding_using_tf(tf_graph, const_node_values)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\tf_utils.py", line 217, in compute_const_folding_using_tf
    mini_graph_def.node.append(node.node_def)
AttributeError: 'RepeatedCompositeFieldContainer' object has no attribute 'append'

Any suggestions/ideas?

**Comment by TomWildenhain-Microsoft** [comment]
Can you try again using opset 11?  Some opsets require inputs to be converted into attributes which fails if the inputs aren't constant (hence the "must be Const" errors).  Higher opsets have these as dynamic inputs so conversion will succeed.

**Comment by ianier** [comment]
> Can you try again using opset 11? Some opsets require inputs to be converted into attributes which fails if the inputs aren't constant (hence the "must be Const" errors). Higher opsets have these as dynamic inputs so conversion will succeed.

@TomWildenhain-Microsoft thanks for looking into this. Just tried the same with --opset 11 and still no luck:

 ERROR - Failed to convert node 'stft/rfft' (fct=<bound method RFFTOp.version_1 of <class 'tf2onnx.onnx_opset.signal.RFFTOp'>>)
'OP=RFFT\nName=stft/rfft\nInputs:\n\tstft/mul:0=Mul, [-1, -1, 4096], 1\n\tstft/rfft/packed:0=Const, [1], 6\nOutpus:\n\tstft/rfft:0=[-1, -1, 2049], 14'
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\tfonnx.py", line 286, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\onnx_opset\signal.py", line 107, in version_1
    consumer_types)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\utils.py", line 213, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Current implementation of RFFT only allows ComplexAbs as consumer not {'Transpose'}
2020-10-12 19:17:25,936 - ERROR - Failed to convert node 'Abs' (fct=<bound method ComplexAbsOp.version_1 of <class 'tf2onnx.onnx_opset.signal.ComplexAbsOp'>>)
'OP=ComplexAbs\nName=Abs\nInputs:\n\tReshape:0=Reshape, [-1, 512, -1, -1], 14\nOutpus:\n\tAbs:0=[-1, 512, -1, -1], 1'
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\tfonnx.py", line 286, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\onnx_opset\signal.py", line 230, in version_1
    cls.any_version(1, ctx, node, **kwargs)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\onnx_opset\signal.py", line 186, in any_version
    utils.make_sure(shape[0] == 2, "ComplexAbs expected the first dimension to be 2 but shape is %r", shape)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\utils.py", line 213, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: ComplexAbs expected the first dimension to be 2 but shape is [-1, 512, -1, -1]
2020-10-12 19:17:26,634 - ERROR - Tensorflow op [inverse_stft_1/irfft: IRFFT] is not supported
2020-10-12 19:17:26,659 - ERROR - Tensorflow op [inverse_stft/irfft: IRFFT] is not supported
2020-10-12 19:17:26,676 - ERROR - Unsupported ops: Counter({'IRFFT': 2})
Traceback (most recent call last):
  File "C:\...\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\...\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\convert.py", line 185, in <module>
    main()
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\convert.py", line 163, in main
    const_node_values=const_node_values)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\tfonnx.py", line 528, in process_tf_graph
    raise exceptions[0]
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\tfonnx.py", line 286, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\onnx_opset\signal.py", line 107, in version_1
    consumer_types)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\tf2onnx\utils.py", line 213, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Current implementation of RFFT only allows ComplexAbs as consumer not {'Transpose'}

**Comment by TomWildenhain-Microsoft** [comment]
Ok so the remaining problems are with complex numbers.  ONNX does not yet support operations on complex numbers so there isn't much we can do to make this model convert currently.  Is this an audio model?  The FFT ops are often part of preprocesing, so if you can cut them out of the graph and do that part in code, you might be OK.  We can convert RFFT if it is followed immediately by an Abs but there's a transpose following it in the graph (and we can't do the IRFFT).  Is there any way you can get rid of the complex ops?

**Comment by ianier** [comment]
@TomWildenhain-Microsoft: Yes, it's an audio model for source separation (e.g. extracting vocals from a mixed track). You're correct on the assumption that FFT/IFFT could be done outside, but unfortunately the "processed" inputs of the model are also complex. 
My ultimate goal is to deploy this model in a UWP app, so I was hoping to convert it to ONNX and use WinML to run it (BTW, opset 11 isn't yet supported on UWP). 
So, the most realistic option at the moment is to link tensorflow statically (possibly through vcpkg) and implement the separation feature only on x64.

**Comment by TomWildenhain-Microsoft** [comment]
Yeah there's some discussion about adding complex ops to ONNX.  We could also hack around it in the converter (composing multiple ops) but that would be a big pain.  @guschmue do you see any other ways around this, or is linking TF the best option for @ianier?

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
