### ISSUE TITLE
Tensorflow SSD mobilenetV1 vs SSD mobilenetV2 to ONNX conversion inconsistency

### ISSUE THREAD

**Issue by alexm-nm** [onnx/tensorflow-onnx#898]
We had converted the following two models from the Tensorflow model zoo to onnx:

1. [ssd_mobilenet_v2_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz)
2. [ssd_mobilenet_v1_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz)

However, we have found a problem with the conversion of ssd_mobilenet_v1_coco. Constant folding is not done properly for the ssd_mobilenet_v1_coco, but it is done properly for ssd_mobilenet_v2_coco.

A snapshot from the viewer Netron is attached for illustration:

**ssd_mobilenet_v1_coco - Here constant folding is not done properly**

<img width="1678" alt="Mobilenet v1 not folded" src="https://user-images.githubusercontent.com/59768536/80291530-42eec600-871c-11ea-884c-1328870ea5d8.png">

**ssd_mobilenet_v2_coco - Here constant folding is ok**

<img width="687" alt="Mobilnet v2 folded" src="https://user-images.githubusercontent.com/59768536/80291533-45e9b680-871c-11ea-87dd-482a6b56274e.png">

We have tried to understand why this happens, however, got stuck and cannot find the reason for why the section shown above in SSD mobilenetv1 is not folded. Any help/hint will be really helpful to us!

**Urgency**
Very important

**System information**
- Ubuntu 16.04
- tensorflow version 1.15
- onnx version 1.6.0
- tf2onnx version 1.6.0/82f805
- python version 3.6
- opset used is 11
- --fold_const flag is used

**Comment by jignparm** [comment]
Thanks for the links to the models, and the diagrams depicting the potential source of const-folding errors.

The 'shape' operator, which is top-most in the red outlined box -- I'm assuming this is const, and everything below is const as well, which is why you are expecting it to be folded?

**Comment by alexm-nm** [comment]
@jignparm yes, it is expected to be just a constant shape, and then everything folds.

**Comment by jignparm** [comment]
Thanks for confirming. Will investigate and update the issue -- these types of optimization gaps,  especially for larger models,  take a bit longer to isolate

**Comment by alexm-nm** [comment]
Thanks @jignparm! Feel free to message if you any other info.

**Comment by jignparm** [comment]
@alexm-nm, I converted both the V1 and V2 models you linked above, and in both models the constant folding seems to be doing a decent job.

See the diagram below -- the yellow highlighted edge feeds directly into the V1 op jungle that you outlined should be const-folded away , presumably because you found that in V2 the operators around the  'Tile' operator look cleaner. 

As you can see, the input dimensions are 'unk__8344...' , which means they will be set dynamically at runtime, and there's no way to const-fold them out.  Hence, I don't see why the operators you outlined in red should be folded, since their input is not a compile-time constant. Let me know if you're seeing something different or have a different interpretation.

Also, I don't think we can visually compare V1 to V2  to get a sense of 'something is missing' in one of the graphs -- these would be quite different models, so we should not expect subgraphs to align up visually. 

However, if you compare V2-unfolded to V2-folded, you'll see that many ops are indeed stripped out -- which indicates that const-folding seems to be working.


![image](https://user-images.githubusercontent.com/13698702/80477215-18c71f00-893b-11ea-89c6-cd6886f6ea3b.png)

**Comment by alexm-nm** [comment]
@jignparm thanks for the thorough check of V1 vs V2. I actually forgot to mention that when we do the conversion to onnx, we apply "shape override" on the input tensor. As a result, the 'unk__8344...' is actually set to specific sizes. Here is command we use for that conversion:

`python -m tf2onnx.convert     --input ~/onnx/ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.pb     --inputs 'image_tensor:0[1,224,224,3]'     --outputs 'detection_boxes:0,detection_scores:0,num_detections:0,detection_classes:0'     --opset 11     --fold_const     --output ~/onnx/ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph_test.onnx`

**Comment by jignparm** [comment]
If the shape is provided, then the branch I posted above (at least some ops) can be folded out -- tf2onnx doesn't fold out the 'Shape' op, but I believe the TF optimizer should have eliminated some of these ops, even before getting to the tf2onnx core logic. Will update shortly.

**Comment by alexm-nm** [comment]
Hi @jignparm ,

You were right about the TF optimizer, the problem was there. We had re-executed the freezing process (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md) for the SSD mobilenetV1 on the latest version of Tensorflow, and it was actually able to fold the problematic part properly. Next we converted to ONNX and it looks the same as SSD mobilenetV2.

So the problem was indeed, as you said, in the TF optimizer. Thanks for pointing this out. The issue is fixed on our side.

**Comment by jignparm** [comment]
@alexm-nm -- what version of TF are you using? 

I used both TF 2.1 and 1.14  , as well as  the **frozen model** and **checkpoint model** , but I still see the original problem. Would be great to know what the solution/process was  -- in case other users face similar issues or if something can be changed in tf2onnx.

**Comment by alexm-nm** [comment]
@jignparm this is the versions dump from the tf2onnx.convert:

```
2020-04-29 13:10:14,407 - INFO - Using tensorflow=1.15.0, onnx=1.6.0, tf2onnx=1.6.0/82f805
2020-04-29 13:10:14,408 - INFO - Using opset <onnx, 11>
```

This is the command I used to convert the checkpoint file to the frozen PB:

```
cd /home/alexm/tf_models/models/research
export PYTHONPATH=`pwd`:`pwd`/slim
export MODEL_DIR=/home/alexm/onnx/ssd_mobilenet_v2_coco_2018_03_29
python object_detection/export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path $MODEL_DIR/pipeline.config \
    --trained_checkpoint_prefix $MODEL_DIR/model.ckpt \
    --output_directory $MODEL_DIR/export_1

```

Then, this is the command I used to convert from frozen PB to ONNX:

```
cd /home/alexm/tf2onnx/tensorflow-onnx
export MODEL_DIR=/home/alexm/onnx/ssd_mobilenet_v2_coco_2018_03_29/export_1
python -m tf2onnx.convert \
    --input $MODEL_DIR/frozen_inference_graph.pb \
    --inputs 'image_tensor:0[1,640,640,3]' \
    --outputs 'detection_boxes:0,detection_scores:0,num_detections:0,detection_classes:0' \
    --opset 11 \
    --fold_const \
    --output $MODEL_DIR/frozen_inference_graph.onnx

```

**Comment by jignparm** [comment]
Thanks @alexm-nm . It seems like youused TF 1.15 and also had to use the `pipeline.config` from the V2 model to re-export the V1 model. There are a few meta files that need to be set up as well, so it's a bit involved (i.e. need some *.record files, running protoc to generate  anchor_generator_pb2  etc.).

> the checkpoint needs to be refrozen again with the latest TF version, so that "latest" TF constant folding is applied

Thanks for updating with a  solution!

Ideally, the TF version would not matter, and the manner of export would not matter either -- there may be hope for a general-purpose solution, but it's great to have one working path for these models.

**Comment by alexm-nm** [comment]
@jignparm yeah, no problem. (btw, I have used the original "pipeline.config" V1 file without any changes)

**Comment by mlinxiang** [comment]
can share the command of convert ssd_mobilenetev2 to onnx?

**Comment by jignparm** [comment]
>can share the command of convert ssd_mobilenetev2 to onnx?

Try the command above (for V1).

**Comment by TUT-jiayou** [comment]
Hi, @mlinxiang 

would you convert ssd_mobilenetev2 to onnx successfully ?  if so, can share the command of convert ssd_mobilenetev2 to onnx?

**Comment by TUT-jiayou** [comment]
Hi, @mlinxiang  @jignparm @alexm-nm 
# I use the commands to convert model, inference successfully inference in the onnxruntime, But can not inference successfully in tensorrt. Would you give me some guide? 
* 1
```
python -m tf2onnx.convert \
    --input $MODEL_DIR/frozen_inference_graph.pb \
    --inputs 'image_tensor:0[1,640,640,3]' \
    --outputs 'detection_boxes:0,detection_scores:0,num_detections:0,detection_classes:0' \
    --opset 11 \
    --fold_const \
```
* 2
```
python -m tf2onnx.convert \
    --input $MODEL_DIR/model.ckpt.meta \
    --inputs 'image_tensor:0[1,640,640,3]' \
    --outputs 'detection_boxes:0,detection_scores:0,num_detections:0,detection_classes:0' \
    --opset 11 \
    --fold_const \
```

# Error
```
----------------------------------------------------------------
Input filename:   frozen_inference_graph.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    tf2onnx
Producer version: 1.9.1
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
Unsupported ONNX data type: UINT8 (2)
ERROR: image_tensor:0:188 In function importInput:
[8] Assertion failed: convertDtype(onnxDtype.elem_type(), &trtDtype)
parse model error
```
# Env
* Ubuntu18.04 
* python 3.7.10
* tensorflow-estimator 1.15.1
* tensorflow-gpu       1.15.5
* onnx                 1.6.0
* onnxruntime          1.3.0
* tf2onnx              1.9.1
* tensorrt 7.1.3

**Comment by TUT-jiayou** [comment]
Hi ,all
can look at https://github.com/onnx/onnx-tensorrt/issues/400
